
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 2G

  aerospike:
    image: aerospike/aerospike-server:latest
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - aerospike_data:/opt/aerospike/data
    environment:
      - NAMESPACE=fraudns
    env_file:
      - .env

  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - aerospike
    # environment:
    #   - OLLAMA_BASE_URL=http://ollama:11434
    #   - AEROSPIKE_HOST=aerospike
    #   - AEROSPIKE_PORT=3000
    env_file:
      - .env
    restart: on-failure

volumes:
  ollama_data:
  aerospike_data: